name: ğŸš€ Release C Project

on:
  push:
    tags:
      - "v*"     # ğŸ”– dÃ©clenche sur chaque tag versionnÃ© ex: v1.0.0

permissions:
  contents: write

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: ğŸ“¥ Checkout repository
        uses: actions/checkout@v4

      - name: ğŸ› ï¸ Install dependencies
        run: choco install make

      - name: ğŸ§± Build with Makefile
        run: make

      - name: ğŸ§½ Clean up build files
        run: make clean-build

      - name: ğŸ—œï¸ Create Zip archive
        run: Compress-Archive -Path build/* -DestinationPath ArtOfCinema-Windows-${{ github.ref_name }}.zip

      - name: ğŸ“¦ Upload build artifact
        uses: actions/upload-artifact@v4
        with:
          name: ArtOfCinema-zip
          path: ArtOfCinema-Windows-${{ github.ref_name }}.zip

  release:
    needs: build
    runs-on: windows-latest

    steps:
      - name: ğŸ“¥ Download artifact
        uses: actions/download-artifact@v4
        with:
          name: ArtOfCinema-zip
          path: .

      - name: ğŸ‰ Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          files: ArtOfCinema-Windows-${{ github.ref_name }}.zip
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
